export const cidOptions = [
  `N/A`,
  `A00 - Cólera`,
  `A01 - Febres tifóide e paratifóide`,
  `A02 - Outras infecções por Salmonella`,
  `A09 - Diarréia e gastroenterite de origem infecciosa presumível`,
  `A15 - Tuberculose respiratória, com confirmação bacteriológica e histológica`,
  `A16 - Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica`,
  `A17 - Tuberculose do sistema nervoso`,
  `A18 - Tuberculose de outros órgãos`,
  `A19 - Tuberculose miliar`,
  `A23 - Brucelose`,
  `A27 - Leptospirose`,
  `A30 - Hanseníase [doença de Hansen] [lepra]`,
  `A31 - Infecções devidas a outras micobactérias`,
  `A41 - Outras septicemias`,
  `A46 - Erisipela`,
  `A48 - Outras doenças bacterianas não classificadas em outra parte`,
  `A49 - Infecção bacteriana de local não especificado`,
  `A70 - Infecções causadas por Clamídia psittaci`,
  `A77 - Febre maculosa [rickettsioses transmitidas por carrapatos]`,
  `A90 - Dengue [dengue clássico]`,
  `B00 - Infecções pelo vírus do herpes [herpes simples]`,
  `B04 - Varíola dos macacos [Monkeypox]`,
  `B15 - Hepatite aguda A`,
  `B17 - Outras hepatites virais agudas`,
  `B18 - Hepatite viral crônica`,
  `B30 - Conjuntivite viral`,
  `B34 - Doenças por vírus, de localização não especificada`,
  `B35 - Dermatofitose`,
  `B36 - Outras micoses superficiais`,
  `B39 - Histoplasmose`,
  `B41 - Paracoccidioidomicose`,
  `B42 - Esporotricose`,
  `B45 - Criptococose`,
  `B49 - Micose não especificada`,
  `B50 - Malária por Plasmodium falciparum`,
  `B51 - Malária por Plasmodium vivax`,
  `B55 - Leishmaniose`,
  `B58 - Toxoplasmose`,
  `B65 - Esquistossomose [bilharziose] [Schistosomíase]`,
  `B69 - Cisticercose`,
  `B86 - Escabiose [sarna]`,
  `B87 - Miíase`,
  `B90 - Seqüelas de tuberculose`,
  `B91 - Seqüelas de poliomielite`,
  `B92 - Seqüelas de hanseníase [lepra]`,
  `B94 - Seqüelas de outras doenças infecciosas e parasitárias e das não especificadas`,
  `C16 - Neoplasia maligna do estômago`,
  `C18 - Neoplasia maligna do cólon`,
  `C23 - Neoplasia maligna da vesícula biliar`,
  `C25 - Neoplasia maligna do pâncreas`,
  `C30 - Neoplasia maligna da cavidade nasal e do ouvido médio`,
  `C32 - Neoplasia maligna da laringe`,
  `C34 - Neoplasia maligna dos brônquios e dos pulmões`,
  `C41 - Neoplasia maligna dos ossos e das cartilagens articulares de outras localizações e de localizações não especificadas`,
  `C44 - Outras neoplasias malignas da pele`,
  `C49 - Neoplasia maligna do tecido conjuntivo e de outros tecidos moles`,
  `C50 - Neoplasia maligna da mama`,
  `C53 - Neoplasia maligna do colo do útero`,
  `C62 - Neoplasia maligna dos testículos`,
  `C67 - Neoplasia maligna da bexiga`,
  `C71 - Neoplasia maligna do encéfalo`,
  `C73 - Neoplasia maligna da glândula tireóide`,
  `C85 - Linfoma não-Hodgkin de outros tipos e de tipo não especificado`,
  `C90 - Mieloma múltiplo e neoplasias malignas de plasmócitos`,
  `C91 - Leucemia linfóide`,
  `C92 - Leucemia mielóide`,
  `C95 - Leucemia de tipo celular não especificado`,
  `D16 - Neoplasia benigna de osso e de cartilagem articular`,
  `D17 - Neoplasia lipomatosa benigna`,
  `D21 - Outras neoplasias benignas do tecido conjuntivo e de outros tecidos moles`,
  `D22 - Nevos melanocíticos`,
  `D23 - Outras neoplasias benignas da pele`,
  `D25 - Leiomioma do útero`,
  `D26 - Outras neoplasias benignas do útero`,
  `D27 - Neoplasia benigna do ovário`,
  `D32 - Neoplasia benigna das meninges`,
  `D33 - Neoplasia benigna do encéfalo e de outras partes do sistema nervoso central`,
  `D37 - Neoplasia de comportamento incerto ou desconhecido da cavidade oral e dos órgãos digestivos`,
  `D43 - Neoplasia de comportamento incerto ou desconhecido do encéfalo e do sistema nervoso central`,
  `D44 - Neoplasia de comportamento incerto ou desconhecido das glândulas endócrinas`,
  `D46 - Síndromes mielodisplásicas`,
  `D47 - Outras neoplasias de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos correlatos`,
  `D48 - Neoplasia de comportamento incerto ou desconhecido de outras localizações e de localizações não especificadas`,
  `D61 - Outras anemias aplásticas`,
  `D68 - Outros defeitos da coagulação`,
  `D69 - Púrpura e outras afecções hemorrágicas`,
  `D73 - Doenças do baço`,
  `D75 - Outras doenças do sangue e dos órgãos hematopoéticos`,
  `D86 - Sarcoidose`,
  `E10 - Diabetes mellitus insulino-dependente`,
  `E11 - Diabetes mellitus não-insulino-dependente`,
  `E13 - Outros tipos especificados de diabetes mellitus`,
  `E14 - Diabetes mellitus não especificado`,
  `E66 - Obesidade`,
  `E75 - Distúrbios do metabolismo de esfingolípides e outros distúrbios de depósito de lípides`,
  `F03 - Demência não especificada`,
  `F06 - Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física`,
  `F07 - Transtornos de personalidade e do comportamento devidos a doença, a lesão e a disfunção cerebral`,
  `F10 - Transtornos mentais e comportamentais devidos ao uso de álcool`,
  `F11 - Transtornos mentais e comportamentais devidos ao uso de opiáceos`,
  `F12 - Transtornos mentais e comportamentais devidos ao uso de canabinóides`,
  `F13 - Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos`,
  `F14 - Transtornos mentais e comportamentais devidos ao uso da cocaína`,
  `F18 - Transtornos mentais e comportamentais devidos ao uso de solventes voláteis`,
  `F19 - Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas`,
  `F20 - Esquizofrenia`,
  `F22 - Transtornos delirantes persistentes`,
  `F23 - Transtornos psicóticos agudos e transitórios`,
  `F25 - Transtornos esquizoafetivos`,
  `F29 - Psicose não-orgânica não especificada`,
  `F30 - Episódio maníaco`,
  `F31 - Transtorno afetivo bipolar`,
  `F32 - Episódios depressivos`,
  `F33 - Transtorno depressivo recorrente`,
  `F34 - Transtornos de humor [afetivos] persistentes`,
  `F38 - Outros transtornos do humor [afetivos]`,
  `F39 - Transtorno do humor [afetivo] não especificado`,
  `F40 - Transtornos fóbico-ansiosos`,
  `F41 - Outros transtornos ansiosos`,
  `F42 - Transtorno obsessivo-compulsivo`,
  `F43 - Reações ao 'stress' grave e transtornos de adaptação`,
  `F44 - Transtornos dissociativos [de conversão]`,
  `F45 - Transtornos somatoformes`,
  `F48 - Outros transtornos neuróticos`,
  `F50 - Transtornos da alimentação`,
  `F51 - Transtornos não-orgânicos do sono devidos a fatores emocionais`,
  `F53 - Transtornos mentais e comportamentais associados ao puerpério, não classificados em outra parte`,
  `F60 - Transtornos específicos da personalidade`,
  `F69 - Transtorno da personalidade e do comportamento do adulto, não especificado`,
  `F72 - Retardo mental grave`,
  `F73 - Retardo mental profundo`,
  `F82 - Transtorno específico do desenvolvimento motor`,
  `F84 - Transtornos globais do desenvolvimento`,
  `F88 - Outros transtornos do desenvolvimento psicológico`,
  `F90 - Transtornos hipercinéticos`,
  `F91 - Distúrbios de conduta`,
  `F92 - Transtornos mistos de conduta e das emoções`,
  `G06 - Abscesso e granuloma intracranianos e intra-raquidianos`,
  `G12 - Atrofia muscular espinal e síndromes correlatas`,
  `G23 - Outras doenças degenerativas dos gânglios da base`,
  `G24 - Distonia`,
  `G35 - Esclerose múltipla`,
  `G40 - Epilepsia`,
  `G41 - Estado de mal epiléptico`,
  `G43 - Enxaqueca`,
  `G44 - Outras síndromes de algias cefálicas`,
  `G45 - Acidentes vasculares cerebrais isquêmicos transitórios e síndromes correlatas`,
  `G46 - Síndromes vasculares cerebrais que ocorrem em doenças cerebrovasculares (I60-I67+)`,
  `G47 - Distúrbios do sono`,
  `G50 - Transtornos do nervo trigêmeo`,
  `G51 - Transtornos do nervo facial`,
  `G53 - Transtornos dos nervos cranianos em doenças classificadas em outra parte`,
  `G54 - Transtornos das raízes e dos plexos nervosos`,
  `G55 - Compressões das raízes e dos plexos nervosos em doenças classificadas em outra parte`,
  `G56 - Mononeuropatias dos membros superiores`,
  `G57 - Mononeuropatias dos membros inferiores`,
  `G58 - Outras mononeuropatias`,
  `G59 - Mononeuropatias em doenças classificadas em outra parte`,
  `G60 - Neuropatia hereditária e idiopática`,
  `G62 - Outras polineuropatias`,
  `G63 - Polineuropatia em doenças classificadas em outra parte`,
  `G64 - Outros transtornos do sistema nervoso periférico`,
  `G71 - Transtornos primários dos músculos`,
  `G72 - Outras miopatias`,
  `G81 - Hemiplegia`,
  `G82 - Paraplegia e tetraplegia`,
  `G83 - Outras síndromes paralíticas`,
  `G90 - Transtornos do sistema nervoso autônomo`,
  `G93 - Outros transtornos do encéfalo`,
  `G95 - Outras doenças da medula espinal`,
  `G96 - Outros transtornos do sistema nervoso central`,
  `G99 - Outros transtornos do sistema nervoso em doenças classificadas em outra parte`,
  `H02 - Outros transtornos da pálpebra`,
  `H05 - Transtornos da órbita`,
  `H10 - Conjuntivite`,
  `H11 - Outros transtornos da conjuntiva`,
  `H15 - Transtornos da esclerótica`,
  `H16 - Ceratite`,
  `H17 - Cicatrizes e opacidades da córnea`,
  `H18 - Outros transtornos da córnea`,
  `H19 - Transtorno da esclerótica e da córnea em doenças classificadas em outra parte`,
  `H20 - Iridociclite`,
  `H21 - Outros transtornos da íris e do corpo ciliar`,
  `H25 - Catarata senil`,
  `H26 - Outras cataratas`,
  `H27 - Outros transtornos do cristalino`,
  `H28 - Catarata e outros transtornos do cristalino em doenças classificadas em outra parte`,
  `H32 - Transtornos coriorretinianos em doenças classificadas em outra parte`,
  `H33 - Descolamentos e defeitos da retina`,
  `H34 - Oclusões vasculares da retina`,
  `H35 - Outros transtornos da retina`,
  `H36 - Transtornos da retina em doenças classificadas em outra parte`,
  `H40 - Glaucoma`,
  `H43 - Transtornos do humor vítreo`,
  `H44 - Transtornos do globo ocular`,
  `H45 - Transtornos do humor vítreo e do globo ocular em doenças classificadas em outra parte`,
  `H46 - Neurite óptica`,
  `H49 - Estrabismo paralítico`,
  `H50 - Outros estrabismos`,
  `H52 - Transtornos da refração e da acomodação`,
  `H53 - Distúrbios visuais`,
  `H54 - Cegueira e visão subnormal`,
  `H57 - Outros transtornos do olho e anexos`,
  `H58 - Outros transtornos do olho e anexos em doenças classificadas em outra parte`,
  `H59 - Transtornos do olho e anexos pós-procedimento não classificados em outra parte`,
  `H60 - Otite externa`,
  `H62 - Transtornos do ouvido externo em doenças classificadas em outra parte`,
  `H65 - Otite média não-supurativa`,
  `H66 - Otite média supurativa e as não especificadas`,
  `H70 - Mastoidite e afecções correlatas`,
  `H72 - Perfuração da membrana do tímpano`,
  `H74 - Outros transtornos do ouvido médio e da mastóide`,
  `H81 - Transtornos da função vestibular`,
  `H83 - Outros transtornos do ouvido interno`,
  `H90 - Perda de audição por transtorno de condução e/ou neuro-sensorial`,
  `H91 - Outras perdas de audição`,
  `H93 - Outros transtornos do ouvido não classificados em outra parte`,
  `I05 - Doenças reumáticas da valva mitral`,
  `I08 - Doenças de múltiplas valvas`,
  `I10 - Hipertensão essencial (primária)`,
  `I12 - Doença renal hipertensiva`,
  `I20 - Angina pectoris`,
  `I21 - Infarto agudo do miocárdio`,
  `I22 - Infarto do miocárdio recorrente`,
  `I24 - Outras doenças isquêmicas agudas do coração`,
  `I25 - Doença isquêmica crônica do coração`,
  `I26 - Embolia pulmonar`,
  `I30 - Pericardite aguda`,
  `I31 - Outras doenças do pericárdio`,
  `I32 - Pericardite em doenças classificadas em outra parte`,
  `I33 - Endocardite aguda e subaguda`,
  `I34 - Transtornos não-reumáticos da valva mitral`,
  `I35 - Transtornos não-reumáticos da valva aórtica`,
  `I36 - Transtornos não-reumáticos da valva tricúspide`,
  `I40 - Miocardite aguda`,
  `I42 - Cardiomiopatias`,
  `I43 - Cardiomiopatia em doenças classificadas em outra parte`,
  `I44 - Bloqueio atrioventricular e do ramo esquerdo`,
  `I45 - Outros transtornos de condução`,
  `I46 - Parada cardíaca`,
  `I47 - Taquicardia paroxística`,
  `I48 - 'Flutter' e fibrilação atrial`,
  `I49 - Outras arritmias cardíacas`,
  `I50 - Insuficiência cardíaca`,
  `I52 - Outras afecções cardíacas em doenças classificadas em outra parte`,
  `I60 - Hemorragia subaracnóide`,
  `I61 - Hemorragia intracerebral`,
  `I62 - Outras hemorragias intracranianas não-traumáticas`,
  `I63 - Infarto cerebral`,
  `I64 - Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico`,
  `I66 - Oclusão e estenose de artérias cerebrais que não resultam em infarto cerebral`,
  `I67 - Outras doenças cerebrovasculares`,
  `I69 - Seqüelas de doenças cerebrovasculares`,
  `I70 - Aterosclerose`,
  `I72 - Outros aneurismas`,
  `I73 - Outras doenças vasculares periféricas`,
  `I74 - Embolia e trombose arteriais`,
  `I77 - Outras afecções das artérias e arteríolas`,
  `I79 - Transtornos das artérias, das arteríolas e dos capilares em doenças classificadas em outra parte`,
  `I80 - Flebite e tromboflebite`,
  `I81 - Trombose da veia porta`,
  `I82 - Outra embolia e trombose venosas`,
  `I83 - Varizes dos membros inferiores`,
  `I84 - Hemorróidas`,
  `I85 - Varizes esofagianas`,
  `I86 - Varizes de outras localizações`,
  `I87 - Outras transtornos das veias`,
  `I89 - Outros transtornos não-infecciosos dos vasos linfáticos e dos gânglios linfáticos`,
  `I99 - Outros transtornos do aparelho circulatório e os não especificados`,
  `J01 - Sinusite aguda`,
  `J04 - Laringite e traqueíte agudas`,
  `J09 - Influenza [gripe] devida a vírus identificado da gripe aviária`,
  `J15 - Pneumonia bacteriana não classificada em outra parte`,
  `J18 - Pneumonia por microorganismo não especificada`,
  `J30 - Rinite alérgica e vasomotora`,
  `J32 - Sinusite crônica`,
  `J34 - Outros transtornos do nariz e dos seios paranasais`,
  `J37 - Laringite e laringotraqueíte crônicas`,
  `J38 - Doenças das cordas vocais e da laringe não classificadas em outra parte`,
  `J39 - Outras doenças das vias aéreas superiores`,
  `J40 - Bronquite não especificada como aguda ou crônica`,
  `J42 - Bronquite crônica não especificada`,
  `J43 - Enfisema`,
  `J44 - Outras doenças pulmonares obstrutivas crônicas`,
  `J45 - Asma`,
  `J47 - Bronquectasia`,
  `J62 - Pneumoconiose devida a poeira que contenham sílica`,
  `J63 - Pneumoconiose devida a outras poeiras inorgânicas`,
  `J64 - Pneumoconiose não especificada`,
  `J66 - Doenças das vias aéreas devida a poeiras orgânicas específicas`,
  `J67 - Pneumonite de hipersensibilidade devida a poeiras orgânicas`,
  `J68 - Afecções respiratórias devidas a inalação de produtos químicos, gases, fumaças e vapores`,
  `J69 - Pneumonite devida a sólidos e líquidos`,
  `J84 - Outras doenças pulmonares intersticiais`,
  `J86 - Piotórax`,
  `J90 - Derrame pleural não classificado em outra parte`,
  `J91 - Derrame pleural em afecções classificadas em outra parte`,
  `J93 - Pneumotórax`,
  `J94 - Outras afecções pleurais`,
  `J95 - Afecções respiratórias pós-procedimentos não classificadas em outra parte`,
  `J96 - Insuficiência respiratória não classificada de outra parte`,
  `J98 - Outros transtornos respiratórios`,
  `J99 - Transtornos respiratórios em doenças classificadas em outra parte`,
  `K07 - Anomalias dentofaciais (inclusive a maloclusão)`,
  `K08 - Outros transtornos dos dentes e de suas estruturas de sustentação`,
  `K10 - Outras doenças dos maxilares`,
  `K20 - Esofagite`,
  `K22 - Outras doenças do esôfago`,
  `K25 - Úlcera gástrica`,
  `K31 - Outras doenças do estômago e do duodeno`,
  `K35 - Apendicite aguda`,
  `K37 - Apendicite, sem outras especificações`,
  `K40 - Hérnia inguinal`,
  `K41 - Hérnia femoral`,
  `K42 - Hérnia umbilical`,
  `K43 - Hérnia ventral`,
  `K44 - Hérnia diafragmática`,
  `K45 - Outras hérnias abdominais`,
  `K46 - Hérnia abdominal não especificada`,
  `K50 - Doença de Crohn [enterite regional]`,
  `K55 - Transtornos vasculares do intestino`,
  `K56 - Íleo paralítico e obstrução intestinal sem hérnia`,
  `K59 - Outros transtornos funcionais do intestino`,
  `K60 - Fissura e fístula das regiões anal e retal`,
  `K61 - Abscesso das regiões anal e retal`,
  `K62 - Outras doenças do reto e do ânus`,
  `K63 - Outras doenças do intestino`,
  `K65 - Peritonite`,
  `K66 - Outros transtornos do peritônio`,
  `K76 - Outras doenças do fígado`,
  `K80 - Colelitíase`,
  `K81 - Colecistite`,
  `K83 - Outras doenças das vias biliares`,
  `K85 - Pancreatite aguda`,
  `K86 - Outras doenças do pâncreas`,
  `K87 - Transtornos da vesícula biliar, das vias biliares e do pâncreas em doenças classificadas em outra parte`,
  `K92 - Outras doenças do aparelho digestivo`,
  `L02 - Abscesso cutâneo, furúnculo e antraz`,
  `L03 - Celulite (Flegmão)`,
  `L04 - Linfadenite aguda`,
  `L05 - Cisto pilonidal`,
  `L08 - Outras infecções localizadas da pele e do tecido subcutâneo`,
  `L13 - Outras afecções bolhosas`,
  `L20 - Dermatite atópica`,
  `L23 - Dermatites alérgicas de contato`,
  `L24 - Dermatites de contato por irritantes`,
  `L25 - Dermatite de contato não especificada`,
  `L28 - Líquen simples crônico e prurigo`,
  `L30 - Outras dermatites`,
  `L40 - Psoríase`,
  `L43 - Líquen plano`,
  `L50 - Urticária`,
  `L51 - Eritema polimorfo (eritema multiforme)`,
  `L55 - Queimadura solar`,
  `L57 - Alterações da pele devidas à exposição crônica à radiação não ionizante`,
  `L59 - Outras afecções da pele e do tecido subcutâneo relacionadas com a radiação`,
  `L60 - Afecções das unhas`,
  `L72 - Cistos foliculares da pele e do tecido subcutâneo`,
  `L73 - Outras afecções foliculares`,
  `L81 - Outros transtornos da pigmentação`,
  `L84 - Calos e calosidades`,
  `L88 - Piodermite gangrenosa`,
  `L89 - Úlcera de decúbito`,
  `L90 - Afecções atróficas da pele`,
  `L91 - Afecções hipertróficas da pele`,
  `L92 - Afecções granulomatosas da pele e do tecido subcutâneo`,
  `L93 - Lúpus eritematoso`,
  `L97 - Úlcera dos membros inferiores não classificada em outra parte`,
  `L98 - Outras afecções da pele e do tecido subcutâneo não classificadas em outra parte`,
  `L99 - Outras afecções da pele e do tecido subcutâneo em doenças classificadas em outra parte`,
  `M00 - Artrite piogênica`,
  `M01 - Infecções diretas da articulação em doenças infecciosas e parasitárias classificadas em outra parte`,
  `M02 - Artropatias reacionais`,
  `M03 - Artropatias pós-infecciosas e reacionais em doenças infecciosas classificadas em outra parte`,
  `M05 - Artrite reumatóide soro-positiva`,
  `M06 - Outras artrites reumatóides`,
  `M07 - Artropatias psoriásicas e enteropáticas`,
  `M08 - Artrite juvenil`,
  `M10 - Gota`,
  `M11 - Outras artropatias por deposição de cristais`,
  `M12 - Outras artropatias especificadas`,
  `M13 - Outras artrites`,
  `M14 - Artropatias em outras doenças classificadas em outra parte`,
  `M15 - Poliartrose`,
  `M16 - Coxartrose [artrose do quadril]`,
  `M17 - Gonartrose [artrose do joelho]`,
  `M18 - Artrose da primeira articulação carpometacarpiana`,
  `M19 - Outras artroses`,
  `M20 - Deformidades adquiridas dos dedos das mãos e dos pés`,
  `M21 - Outras deformidades adquiridas dos membros`,
  `M22 - Transtornos da rótula [patela]`,
  `M23 - Transtornos internos dos joelhos`,
  `M24 - Outras transtornos articulares específicos`,
  `M25 - Outros transtornos articulares não classificados em outra parte`,
  `M31 - Outras vasculopatias necrotizantes`,
  `M32 - Lúpus eritematoso disseminado [sistêmico]`,
  `M33 - Dermatopoliomiosite`,
  `M35 - Outras afecções sistêmicas do tecido conjuntivo`,
  `M36 - Doenças sistêmicas do tecido conjuntivo em doenças classificadas em outra parte`,
  `M40 - Cifose e lordose`,
  `M41 - Escoliose`,
  `M42 - Osteocondrose da coluna vertebral`,
  `M43 - Outras dorsopatias deformantes`,
  `M45 - Espondilite ancilosante`,
  `M46 - Outras espondilopatias inflamatórias`,
  `M47 - Espondilose`,
  `M48 - Outras espondilopatias`,
  `M50 - Transtornos dos discos cervicais`,
  `M51 - Outros transtornos de discos intervertebrais`,
  `M53 - Outras dorsopatias não classificadas em outra parte`,
  `M54 - Dorsalgia`,
  `M60 - Miosite`,
  `M61 - Calcificação e ossificação do músculo`,
  `M62 - Outros transtornos musculares`,
  `M63 - Transtornos de músculo em doenças classificadas em outra parte`,
  `M65 - Sinovite e tenossinovite`,
  `M66 - Ruptura espontânea de sinóvia e de tendão`,
  `M67 - Outros transtornos das sinóvias e dos tendões`,
  `M68 - Transtorno de sinóvias e de tendões em doenças classificadas em outra parte`,
  `M70 - Transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão`,
  `M71 - Outras bursopatias`,
  `M72 - Transtornos fibroblásticos`,
  `M73 - Transtornos dos tecidos moles em doenças classificadas em outra parte`,
  `M75 - Lesões do ombro`,
  `M76 - Entesopatias dos membros inferiores, excluindo pé`,
  `M77 - Outras entesopatias`,
  `M79 - Outros transtornos dos tecidos moles, não classificados em outra parte`,
  `M80 - Osteoporose com fratura patológica`,
  `M81 - Osteoporose sem fratura patológica`,
  `M82 - Osteoporose em doenças classificadas em outra parte`,
  `M83 - Osteomalácia do adulto`,
  `M84 - Transtornos da continuidade do osso`,
  `M85 - Outros transtornos da densidade e da estrutura ósseas`,
  `M86 - Osteomielite`,
  `M87 - Osteonecrose`,
  `M89 - Outros transtornos ósseos`,
  `M92 - Outras osteocondroses juvenis`,
  `M93 - Outras osteocondropatias`,
  `M94 - Outros transtornos das cartilagens`,
  `M95 - Outras deformidades adquiridas do sistema osteomuscular e do tecido conjuntivo`,
  `M96 - Transtornos osteomusculares pós-procedimentos não classificados em outra parte`,
  `M99 - Lesões biomecânicas não classificadas em outra parte`,
  `N04 - Síndrome nefrótica`,
  `N10 - Nefrite túbulo-intersticial aguda`,
  `N14 - Afecções tubulares e túbulo-intersticiais induzidas por drogas ou metais pesados`,
  `N17 - Insuficiência renal aguda`,
  `N18 - Insuficiência renal crônica`,
  `N20 - Calculose do rim e do ureter`,
  `N31 - Disfunções neuromusculares da bexiga não classificados em outra parte`,
  `N35 - Estenose da uretra`,
  `N36 - Outros transtornos da uretra`,
  `N39 - Outros transtornos do trato urinário`,
  `N44 - Torção do testículo`,
  `N45 - Orquite e epididimite`,
  `N47 - Hipertrofia do prepúcio, fimose e parafimose`,
  `N48 - Outros transtornos do pênis`,
  `N49 - Transtornos inflamatórios de órgãos genitais masculinos, não classificados em outra parte`,
  `N50 - Outros transtornos dos órgãos genitais masculinos`,
  `N51 - Transtornos dos órgãos genitais masculinos em doenças classificadas em outra parte`,
  `N61 - Transtornos inflamatórios da mama`,
  `N62 - Hipertrofia da mama`,
  `N83 - Transtornos não-inflamatórios do ovário, da trompa de Falópio e do ligamento largo`,
  `N87 - Displasia do colo do útero`,
  `N88 - Outros transtornos não-inflamatórios do colo do útero`,
  `N90 - Outros transtornos não-inflamatórios da vulva e do períneo`,
  `O13 - Hipertensão gestacional [induzida pela gravidez] sem proteinúria significativa`,
  `O20 - Hemorragia do início da gravidez`,
  `O21 - Vômitos excessivos na gravidez`,
  `O24 - Diabetes mellitus na gravidez`,
  `O26 - Assistência materna por outras complicações ligadas predominantemente a gravidez`,
  `O34 - Assistência prestada à mãe por anormalidade, conhecida ou suspeita, dos órgãos pélvicos maternos`,
  `O36 - Assistência prestada à mãe por outros problemas fetais conhecidos ou suspeitados`,
  `O45 - Descolamento prematuro da placenta [abruptio placentae]`,
  `O60 - Parto pré-termo`,
  `O99 - Outras doenças da mãe, classificadas em outra parte, mas que complicam a gravidez o parto e o puerpério`,
  `P91 - Outros distúrbios da função cerebral do recém-nascido`,
  `Q05 - Espinha bífida`,
  `Q07 - Outras malformações congênitas do sistema nervoso`,
  `Q25 - Malformações congênitas das grandes artérias`,
  `Q28 - Outras malformações congênitas do aparelho circulatório`,
  `Q65 - Malformações congênitas do quadril`,
  `Q66 - Deformidades congênitas do pé`,
  `Q70 - Sindactilia`,
  `Q72 - Defeitos, por redução, do membro inferior`,
  `Q74 - Outras malformações congênitas dos membros`,
  `Q78 - Outras osteocondrodisplasias`,
  `Q85 - Facomatoses não classificadas em outra parte`,
  `R02 - Gangrena não classificada em outra parte`,
  `R05 - Tosse`,
  `R06 - Anormalidades da respiração`,
  `R07 - Dor de garganta e no peito`,
  `R10 - Dor abdominal e pélvica`,
  `R20 - Distúrbios da sensibilidade cutânea`,
  `R22 - Tumefação, massa ou tumoração localizadas da pele e do tecido subcutâneo`,
  `R26 - Anormalidades da marcha e da mobilidade`,
  `R31 - Hematúria não especificada`,
  `R32 - Incontinência urinária não especificada`,
  `R41 - Outros sintomas e sinais relativos à função cognitiva e à consciência`,
  `R42 - Tontura e instabilidade`,
  `R44 - Outros sintomas e sinais relativos às sensações e às percepções gerais`,
  `R45 - Sintomas e sinais relativos ao estado emocional`,
  `R49 - Distúrbios da voz`,
  `R51 - Cefaléia`,
  `R52 - Dor não classificada em outra parte`,
  `R53 - Mal estar, fadiga`,
  `R55 - Síncope e colapso`,
  `R56 - Convulsões, não classificadas em outra parte`,
  `R57 - Choque não classificado em outra parte`,
  `R60 - Edema não classificado em outra parte`,
  `R69 - Causas desconhecidas e não especificadas de morbidade`,
  `S00 - Traumatismo superficial da cabeça`,
  `S01 - Ferimento da cabeça`,
  `S02 - Fratura do crânio e dos ossos da face`,
  `S03 - Luxação, entorse ou distensão das articulações e dos ligamentos da cabeça`,
  `S04 - Traumatismo dos nervos cranianos`,
  `S05 - Traumatismo do olho e da órbita ocular`,
  `S06 - Traumatismo intracraniano`,
  `S07 - Lesões por esmagamento da cabeça`,
  `S08 - Amputação traumática de parte da cabeça`,
  `S09 - Outros traumatismos da cabeça e os não especificados`,
  `S10 - Traumatismo superficial do pescoço`,
  `S11 - Ferimento do pescoço`,
  `S12 - Fratura do pescoço`,
  `S13 - Luxação, entorse ou distensão das articulações e dos ligamentos do pescoço`,
  `S14 - Traumatismo de nervos e da medula espinhal ao nível cervical`,
  `S15 - Traumatismo dos vasos sangüíneos ao nível do pescoço`,
  `S16 - Traumatismo de tendões e de músculos do pescoço`,
  `S17 - Lesões por esmagamento do pescoço`,
  `S19 - Outros traumatismos do pescoço e os não especificados`,
  `S20 - Traumatismo superficial do tórax`,
  `S21 - Ferimento do tórax`,
  `S22 - Fratura de costela(s), esterno e coluna torácica`,
  `S23 - Luxação, entorse e distensão de articulações e dos ligamentos do tórax`,
  `S24 - Traumatismos de nervos e da medula espinhal ao nível do tórax`,
  `S25 - Traumatismo de vasos sangüíneos do tórax`,
  `S26 - Traumatismo do coração`,
  `S27 - Traumatismo de outros órgãos intratorácicos e dos não especificados`,
  `S28 - Lesão por esmagamento do tórax e amputação traumática de parte do tórax`,
  `S29 - Outros traumatismos do tórax e os não especificados`,
  `S30 - Traumatismo superficial do abdome, do dorso e da pelve`,
  `S31 - Ferimento do abdome, do dorso e da pelve`,
  `S32 - Fratura da coluna lombar e da pelve`,
  `S33 - Luxação, entorse ou distensão das articulações e dos ligamentos da coluna lombar e da pelve`,
  `S34 - Traumatismo dos nervos e da medula lombar ao nível do abdome, do dorso e da pelve`,
  `S35 - Traumatismo de vasos sangüíneos ao nível do abdome, do dorso e da pelve`,
  `S36 - Traumatismo de órgãos intra-abdominais`,
  `S37 - Traumatismo do aparelho urinário e de órgãos pélvicos`,
  `S38 - Lesão por esmagamento e amputação traumática de parte do abdome, do dorso e da pelve`,
  `S39 - Outros traumatismos e os não especificados do abdome, do dorso e da pelve`,
  `S40 - Traumatismo superficial do ombro e do braço`,
  `S41 - Ferimento do ombro e do braço`,
  `S42 - Fratura do ombro e do braço`,
  `S43 - Luxação, entorse e distensão das articulações e dos ligamentos da cintura escapular`,
  `S44 - Traumatismo de nervos ao nível do ombro e do braço`,
  `S45 - Traumatismo dos vasos sangüíneos ao nível do ombro e do braço`,
  `S46 - Traumatismo de tendão e músculo ao nível do ombro e do braço`,
  `S47 - Lesão por esmagamento do ombro e do braço`,
  `S48 - Amputação traumática do ombro e do braço`,
  `S49 - Outros traumatismos e os não especificados do ombro e do braço`,
  `S50 - Traumatismo superficial do cotovelo e do antebraço`,
  `S51 - Ferimento do antebraço`,
  `S52 - Fratura do antebraço`,
  `S53 - Luxação, entorse e distensão das articulações e dos ligamentos do cotovelo`,
  `S54 - Traumatismo de nervos ao nível do antebraço`,
  `S55 - Traumatismo de vasos sangüíneos ao nível do antebraço`,
  `S56 - Traumatismo do músculo e tendão ao nível do antebraço`,
  `S57 - Lesão por esmagamento do antebraço`,
  `S58 - Amputação traumática do cotovelo e do antebraço`,
  `S59 - Outros traumatismos do antebraço e os não especificados`,
  `S60 - Traumatismo superficial do punho e da mão`,
  `S61 - Ferimento do punho e da mão`,
  `S62 - Fratura ao nível do punho e da mão`,
  `S63 - Luxação, entorse e distensão das articulações e dos ligamentos ao nível do punho e da mão`,
  `S64 - Traumatismo de nervos ao nível do punho e da mão`,
  `S65 - Traumatismo de vasos sangüíneos ao nível do punho e da mão`,
  `S66 - Traumatismo de músculo e tendão ao nível do punho e da mão`,
  `S67 - Lesão por esmagamento do punho e da mão`,
  `S68 - Amputação traumática ao nível do punho e da mão`,
  `S69 - Outros traumatismos e os não especificados do punho e da mão`,
  `S70 - Traumatismo superficial do quadril e da coxa`,
  `S71 - Ferimento do quadril e da coxa`,
  `S72 - Fratura do fêmur`,
  `S73 - Luxação, entorse e distensão da articulação e dos ligamentos do quadril`,
  `S74 - Traumatismo de nervos ao nível do quadril e da coxa`,
  `S75 - Traumatismo de vasos sangüíneos ao nível do quadril e da coxa`,
  `S76 - Traumatismo de músculo e de tendão ao nível do quadril e da coxa`,
  `S77 - Lesão por esmagamento do quadril e da coxa`,
  `S78 - Amputação traumática do quadril e da coxa`,
  `S79 - Outros traumatismos e os não especificados do quadril e da coxa`,
  `S80 - Traumatismo superficial da perna`,
  `S81 - Ferimento da perna`,
  `S82 - Fratura da perna, incluindo tornozelo`,
  `S83 - Luxação, entorse e distensão das articulações e dos ligamentos do joelho`,
  `S84 - Traumatismo de nervos periféricos da perna`,
  `S85 - Traumatismo de vasos sangüíneos da perna`,
  `S86 - Traumatismos de músculo e de tendão ao nível da perna`,
  `S87 - Traumatismo por esmagamento da perna`,
  `S88 - Amputação traumática da perna`,
  `S89 - Outros traumatismos e os não especificados da perna`,
  `S90 - Traumatismo superficial do tornozelo e do pé`,
  `S91 - Ferimentos do tornozelo e do pé`,
  `S92 - Fratura do pé (exceto do tornozelo)`,
  `S93 - Luxação, entorse e distensão das articulações e dos ligamentos ao nível do tornozelo e do pé`,
  `S94 - Traumatismo dos nervos ao nível do tornozelo e do pé`,
  `S95 - Traumatismo de vasos sangüíneos ao nível do tornozelo e do pé`,
  `S96 - Traumatismos do músculo e tendão ao nível do tornozelo e do pé`,
  `S97 - Lesão por esmagamento do tornozelo e do pé`,
  `S98 - Amputação traumática do tornozelo e do pé`,
  `S99 - Outros traumatismos e os não especificados do tornozelo e do pé`,
  `T00 - Traumatismos superficiais envolvendo múltiplas regiões do corpo`,
  `T01 - Ferimentos envolvendo múltiplas regiões do corpo`,
  `T02 - Fraturas envolvendo múltiplas regiões do corpo`,
  `T03 - Luxações, entorses e distensões envolvendo regiões múltiplas do corpo`,
  `T04 - Traumatismos por esmagamento envolvendo múltiplas regiões do corpo`,
  `T05 - Amputações traumáticas envolvendo múltiplas regiões do corpo`,
  `T06 - Outros traumatismos envolvendo regiões múltiplas do corpo, não classificados em outra parte`,
  `T07 - Traumatismos múltiplos não especificados`,
  `T08 - Fratura da coluna, nível não especificado`,
  `T09 - Outros traumatismos de coluna e tronco, nível não especificado`,
  `T10 - Fratura do membro superior, nível não especificado`,
  `T11 - Outros traumatismos de membro superior, nível não especificado`,
  `T12 - Fratura do membro inferior, nível não especificado`,
  `T13 - Outros traumatismos de membro inferior, nível não especificado`,
  `T14 - Traumatismo de região não especificada do corpo`,
  `T15 - Corpo estranho na parte externa do olho`,
  `T18 - Corpo estranho no aparelho digestivo`,
  `T19 - Corpo estranho no trato geniturinário`,
  `T20 - Queimadura e corrosão da cabeça e pescoço`,
  `T21 - Queimadura e corrosão do tronco`,
  `T22 - Queimadura e corrosão do ombro e membro superior, exceto punho e mão`,
  `T23 - Queimadura e corrosão do punho e da mão`,
  `T24 - Queimadura e corrosão do quadril e membro inferior, exceto tornozelo e do pé`,
  `T25 - Queimadura e corrosão do tornozelo e do pé`,
  `T26 - Queimadura e corrosão limitadas ao olho e seus anexos`,
  `T27 - Queimadura e corrosão do trato respiratório`,
  `T28 - Queimadura e corrosão de outros órgãos internos`,
  `T29 - Queimaduras e corrosões de múltiplas regiões do corpo`,
  `T30 - Queimadura e corrosão, parte não especificada do corpo`,
  `T31 - Queimaduras classificadas segundo a extensão da superfície corporal atingida`,
  `T32 - Corrosões classificadas segundo a extensão da superfície corporal atingida`,
  `T33 - Geladura superficial`,
  `T34 - Geladura com necrose de tecidos`,
  `T40 - Intoxicação por narcóticos e psicodislépticos [alucinógenos]`,
  `T52 - Efeito tóxico de solventes orgânicos`,
  `T56 - Efeito tóxico de metais`,
  `T59 - Efeito tóxico de outros gases, fumaças e vapores`,
  `T60 - Efeito tóxico de pesticidas`,
  `T63 - Efeito tóxico de contato com animais venenosos`,
  `T64 - Efeito tóxico da aflatoxina e de outras micotoxinas contaminantes de alimentos`,
  `T65 - Efeito tóxico de outras substâncias e as não especificadas`,
  `T70 - Efeitos da pressão atmosférica e da pressão da água`,
  `T74 - Síndromes de maus tratos`,
  `T75 - Efeitos de outras causas externas`,
  `T78 - Efeitos adversos não classificados em outra parte`,
  `T79 - Algumas complicações precoces dos traumatismos não classificadas em outra parte`,
  `T81 - Complicações de procedimentos não classificadas em outra parte`,
  `T82 - Complicações de dispositivos protéticos, implantes e enxertos cardíacos e vasculares`,
  `T84 - Complicações de dispositivos protéticos, implantes e enxertos ortopédicos internos`,
  `T85 - Complicações de outros dispositivos protéticos, implantes e enxertos internos`,
  `T87 - Complicações próprias de reimplante e amputação`,
  `T88 - Outras complicações de cuidados médicos e cirúrgicos não classificadas em outra parte`,
  `T90 - Seqüelas de traumatismo da cabeça`,
  `T91 - Seqüelas de traumatismos do pescoço e do tronco`,
  `T92 - Seqüelas de traumatismos do membro superior`,
  `T93 - Seqüelas de traumatismos do membro inferior`,
  `T94 - Seqüelas de traumatismos envolvendo múltiplas regiões do corpo e as não especificadas`,
  `T95 - Seqüelas de queimaduras, corrosões e geladuras`,
  `T96 - Seqüelas de intoxicação por drogas, medicamentos e substâncias biológicas`,
  `T97 - Seqüelas de efeitos tóxicos de substâncias de origem predominantemente não-medicinal`,
  `T98 - Seqüelas de outros efeitos de causas externas e dos não especificados`,
  `V01 - Pedestre traumatizado em colisão com um veículo a pedal`,
  `V02 - Pedestre traumatizado em colisão com um veículo a motor de duas ou três rodas`,
  `V03 - Pedestre traumatizado em colisão com um automóvel [carro], 'pick up' ou caminhonete`,
  `V04 - Pedestre traumatizado em colisão com um veículo de transporte pesado ou com um ônibus`,
  `V06 - Pedestre traumatizado em colisão com outro veículo não-motorizado`,
  `V09 - Pedestre traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados`,
  `V10 - Ciclista traumatizado em colisão com um pedestre ou um animal`,
  `V11 - Ciclista traumatizado em colisão com outro veículo a pedal`,
  `V12 - Ciclista traumatizado em colisão com um veículo a motor de duas ou três rodas`,
  `V13 - Ciclista traumatizado em colisão com um automóvel, 'pick up' ou caminhonete`,
  `V14 - Ciclista traumatizado em colisão com um veículo de transporte pesado ou um ônibus`,
  `V16 - Ciclista traumatizado em colisão com outro veículo não-motorizado`,
  `V17 - Ciclista traumatizado em colisão com um objeto fixo ou parado`,
  `V18 - Ciclista traumatizado em um acidente de transporte sem colisão`,
  `V19 - Ciclista traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados`,
  `V20 - Motociclista traumatizado em colisão com um pedestre ou um animal`,
  `V21 - Motociclista traumatizado em colisão com um veículo a pedal`,
  `V22 - Motociclista traumatizado em colisão com um veículo a motor de duas ou três rodas`,
  `V23 - Motociclista traumatizado em colisão com um automóvel [carro], 'pick up' ou caminhonete`,
  `V24 - Motociclista traumatizado em colisão com um veículo de transporte pesado ou um ônibus`,
  `V26 - Motociclista traumatizado em colisão com outro veículo não-motorizado`,
  `V27 - Motociclista traumatizado em colisão com um objeto fixo ou parado`,
  `V28 - Motociclista traumatizado em um acidente de transporte sem colisão`,
  `V29 - Motociclista traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados`,
  `V40 - Ocupante de um automóvel [carro] traumatizado em colisão com um pedestre ou um animal`,
  `V41 - Ocupante de um automóvel [carro] traumatizado em colisão com um veículo a pedal`,
  `V42 - Ocupante de um automóvel [carro] traumatizado em colisão com outro veículo a motor de duas ou três rodas`,
  `V43 - Ocupante de um automóvel [carro] traumatizado em colisão com um automóvel [carro], 'pick up' ou caminhonete`,
  `V44 - Ocupante de um automóvel [carro] traumatizado em colisão com um veículo de transporte pesado ou um ônibus`,
  `V47 - Ocupante de um automóvel [carro] traumatizado em colisão com um objeto fixo ou parado`,
  `V48 - Ocupante de um automóvel [carro] traumatizado em um acidente de transporte sem colisão`,
  `V49 - Ocupante de um automóvel [carro] traumatizado em outro acidentes de transporte e em acidentes de transporte não especificados`,
  `V58 - Ocupante de uma caminhonete traumatizado em um acidente de transporte sem colisão`,
  `V59 - Ocupante de uma caminhonete traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados`,
  `V64 - Ocupante de um veículo de transporte pesado traumatizado em colisão com um outro veículo de transporte pesado ou um ônibus`,
  `V67 - Ocupante de um veículo de transporte pesado traumatizado em colisão com um objeto fixo ou parado`,
  `V68 - Ocupante de um veículo de transporte pesado traumatizado em um acidente de transporte sem colisão`,
  `V69 - Ocupante de um veículo de transporte pesado traumatizado em outros acidentes de transporte não especificados`,
  `V74 - Ocupante de um ônibus traumatizado em colisão com um veículo de transporte pesado ou um ônibus`,
  `V78 - Ocupante de um ônibus traumatizado em um acidente de transporte sem colisão`,
  `V79 - Ocupante de um ônibus traumatizado em outros acidentes de transporte e em acidentes de transporte não especificados`,
  `V80 - Pessoa montada em animal ou ocupante de um veículo a tração animal traumatizado em um acidente de transporte`,
  `V84 - Ocupante de um veículo especial a motor de uso essencialmente agrícola traumatizado em um acidente de transporte`,
  `V87 - Acidente de trânsito de tipo especificado, mas sendo desconhecido o modo de transporte da vítima`,
  `V89 - Acidente com um veículo a motor ou não-motorizado, tipo(s) de veículo(s) não especificado(s)`,
  `V95 - Acidente de aeronave a motor causando traumatismo ao ocupante`,
  `V99 - Acidente de transporte não especificado`,
  `W01 - Queda no mesmo nível por escorregão, tropeção ou passos em falsos [traspés]`,
  `W04 - Queda, enquanto estava sendo carregado ou apoiado por outra(s) pessoa(s)`,
  `W07 - Queda de uma cadeira`,
  `W08 - Queda de outro tipo de mobília`,
  `W10 - Queda em ou de escadas ou degraus`,
  `W11 - Queda em ou de escadas de mão`,
  `W12 - Queda em ou de um andaime`,
  `W13 - Queda de ou para fora de edifícios ou outras estruturas`,
  `W14 - Queda de árvore`,
  `W17 - Outras quedas de um nível a outro`,
  `W18 - Outras quedas no mesmo nível`,
  `W19 - Queda sem especificação`,
  `W20 - Impacto causado por objeto lançado, projetado ou em queda`,
  `W21 - Impacto acidental ativo ou passivo causado por equipamento esportivo`,
  `W22 - Impacto acidental ativo ou passivo causado por outros objetos`,
  `W23 - Apertado, colhido, comprimido ou esmagado dentro de ou entre objetos`,
  `W25 - Contato com vidro cortante`,
  `W26 - Contato com faca, espada e punhal`,
  `W29 - Contato com outros utensílios manuais e aparelhos domésticos equipados com motor`,
  `W30 - Contato com maquinaria agrícola`,
  `W31 - Contato com outras máquinas e com as não especificadas`,
  `W32 - Projétil de revólver`,
  `W38 - Explosão ou ruptura de outros aparelhos pressurizados especificados`,
  `W40 - Explosão de outros materiais`,
  `W44 - Penetração de corpo estranho no ou através de olho ou orifício natural`,
  `W45 - Penetração de corpo ou objeto estranho através da pele`,
  `W50 - Golpe, pancada, pontapé, mordedura ou escoriação infligidos por outra pessoa`,
  `W54 - Mordedura ou golpe provocado por cão`,
  `W55 - Mordedura ou golpe provocado por outros animais mamíferos`,
  `W57 - Mordeduras e picadas de inseto e de outros artrópodes, não-venenosos`,
  `W79 - Inalação e ingestão de alimentos causando obstrução do trato respiratório`,
  `W85 - Exposição a linhas de transmissão de corrente elétrica`,
  `W86 - Exposição a outra corrente elétrica especificada`,
  `W87 - Exposição a corrente elétrica não especificada`,
  `W93 - Exposição a um frio excessivo de origem artificial`,
  `X10 - Contato com bebidas, alimentos, gordura e óleo de cozinha quentes`,
  `X12 - Contato com outros líquidos quentes`,
  `X20 - Contato com serpentes e lagartos venenosos`,
  `X21 - Contato com aranhas venenosas`,
  `X22 - Contato com escorpiões`,
  `X27 - Contato com outros animais venenosos especificados`,
  `X29 - Contato com animais ou plantas venenosos, sem especificação`,
  `X46 - Envenenamento [intoxicação] acidental por e exposição a solventes orgânicos e hidrocarbonetos halogenados e seus vapores`,
  `X47 - Intoxicação acidental por e exposição a outros gases e vapores`,
  `X48 - Envenenamento [intoxicação] acidental por e exposição a pesticidas`,
  `X49 - Envenenamento [intoxicação] acidental por e exposição a outras substâncias químicas nocivas e às não especificadas`,
  `X50 - Excesso de exercícios e movimentos vigorosos ou repetitivos`,
  `X59 - Exposição a fatores não especificados`,
  `X69 - Auto-intoxicação por e exposição, intencional, a outros produtos químicos e substâncias nocivas não especificadas`,
  `X78 - Lesão autoprovocada intencionalmente por objeto cortante ou penetrante`,
  `X90 - Agressão por meio de produtos químicos e substâncias nocivas não especificados`,
  `X93 - Agressão por meio de disparo de arma de fogo de mão`,
  `X94 - Agressão por meio de disparo de espingarda, carabina ou arma de fogo de maior calibre`,
  `X95 - Agressão por meio de disparo de outra arma de fogo ou de arma não especificada`,
  `X96 - Agressão por meio de material explosivo`,
  `X99 - Agressão por meio de objeto cortante ou penetrante`,
  `Y00 - Agressão por meio de um objeto contundente`,
  `Y03 - Agressão por meio de impacto de um veículo a motor`,
  `Y04 - Agressão por meio de força corporal`,
  `Y09 - Agressão por meios não especificados`,
  `Y14 - Envenenamento [intoxicação] por e exposição a outras drogas, medicamentos e substâncias biológicas e as não especificadas, intenção não determinada`,
  `Y18 - Envenenamento [intoxicação] por e exposição a pesticidas, intenção não determinada`,
  `Y19 - Envenenamento [intoxicação] por e exposição a outros produtos químicos e substâncias nocivas e aos não especificados, intenção não determinada`,
  `Y20 - Enforcamento, estrangulamento e sufocação, intenção não determinada`,
  `Y28 - Contato com objeto cortante ou penetrante, intenção não determinada`,
  `Y29 - Contato com objeto contundente, intenção não determinada`,
  `Y30 - Queda, salto ou empurrado de um lugar elevado, intenção não determinada`,
  `Y34 - Fatos ou eventos não especificados e intenção não determinada`,
  `Y60 - Corte, punção, perfuração ou hemorragia acidentais durante a prestação de cuidados médicos ou cirúrgicos`,
  `Y82 - Outros dispositivos (aparelhos) associados a incidentes adversos e os não especificados`,
  `Y83 - Reação anormal em paciente ou complicação tardia, causadas por intervenção cirúrgica e por outros atos cirúrgicos, sem menção de acidente durante a intervenção`,
  `Y85 - Seqüelas de acidentes de transporte`,
  `Y88 - Seqüelas de cuidado médico ou cirúrgico considerados como uma causa externa`,
  `Y89 - Seqüelas de outras causas externas`,
  `Y96 - Circunstância relativa às condições de trabalho`,
  `Y98 - Circunstâncias relativas a condições do modo de vida`,
  `Z00 - Exame geral e investigação de pessoas sem queixas ou diagnóstico relatado`,
  `Z01 - Outros exames e investigações especiais de pessoas sem queixa ou diagnóstico relatado`,
  `Z02 - Exame médico e consulta com finalidades administrativas`,
  `Z03 - Observação e avaliação médica por doenças e afecções suspeitas`,
  `Z04 - Exame e observação por outras razões`,
  `Z09 - Exame de seguimento após tratamento de outras afecções que não neoplasias malignas`,
  `Z10 - Exame geral de rotina ('check up') de uma subpopulação definida`,
  `Z20 - Contato com e exposição a doenças transmissíveis`,
  `Z32 - Exame ou teste de gravidez`,
  `Z34 - Supervisão de gravidez normal`,
  `Z35 - Supervisão de gravidez de alto risco`,
  `Z41 - Procedimentos para outros propósitos exceto cuidados de saúde`,
  `Z42 - Seguimento envolvendo cirurgia plástica`,
  `Z43 - Atenção a orifícios artificiais`,
  `Z47 - Outros cuidados de seguimento ortopédico`,
  `Z48 - Outro seguimento cirúrgico`,
  `Z50 - Cuidados envolvendo o uso de procedimentos de reabilitação`,
  `Z51 - Outros cuidados médicos`,
  `Z53 - Pessoas em contato com serviços de saúde para procedimentos específicos não realizados`,
  `Z54 - Convalescença`,
  `Z56 - Problemas relacionados com o emprego e com o desemprego`,
  `Z57 - Exposição ocupacional a fatores de risco`,
  `Z60 - Problemas relacionados com o meio social`,
  `Z63 - Outros problemas relacionados com o grupo primário de apoio, inclusive com a situação familiar`,
  `Z65 - Problemas relacionados com outras circunstâncias psicossociais`,
  `Z73 - Problemas relacionados com a organização de seu modo de vida`,
  `Z76 - Pessoas em contato com os serviços de saúde em outras circunstâncias`,
  `Z89 - Ausência adquirida de membros`,
  `Z90 - Ausência adquirida de órgãos não classificados em outra parte`,
  `Z93 - Orifícios artificiais`,
  `Z94 - Órgãos e tecidos transplantados`,
  `Z96 - Presença de outros implantes funcionais`,
  `Z97 - Presença de outros dispositivos protéticos`,
  `Z98 - Outros estados pós-cirúrgicos`,
];
