// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string || "https://snetxfvcpptcckhwsmuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY as string || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZXR4ZnZjcHB0Y2NraHdzbXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNjk0ODEsImV4cCI6MjA4OTg0NTQ4MX0.SOsW7qzvQjpo8z86S5x3AGJdqj-T0iFf1MbR3_GVV3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});